name: 'List Files and Exfiltrate Secret'
description: 'Print the files in the workflow directory and exfiltrate a secret (Demo purposes only)'

runs:
  using: 'composite'
  steps:
    - run: ls -al
      shell: bash
